### ISSUE TITLE
DB 설계 

### ISSUE THREAD

**Issue by juajang** [Sooktube/Sooktube#1]
API목록:

[GET] api/list : 재생목록들을 보여주는 api 
[GET] 사용자가 좋아요한 재생목록만 보여주는 api 
[GET] api/list/listID?userID={userID} -> 재생목록에 포함된 비디오를 보여줌, 좋아요 눌렀는지 안 눌렀는지에 대한 정보도 포함 { like 여부, { { video: 1, videoTitle: 2}, { } … } } 
[POST] 재생목록 생성 API

[GET] 비디오 아이디에 대한 비디오 정보를 불러오는 api  
[POST] 동영상 업로드 api
[GET] 동영상 재생 api(영상확인)
[DELETE] 동영상 삭제 API
[UPDATE] 동영상 제목/설명 수정 API

영상 DB : 
videoID : 비디오 아이디
videoTitle :비디오 제목 
videoDesc : 비디오에 대한 짧은 설명 
videoDate: 비디오 생성 날짜 //사용자가 넣는게 아니라 지금 날짜를 자등으로 들어가게 
videoPath: 영상 저장 경로
userID: 업로더(user테이블) //저장된 값을 이용 
username

영상 comments:
videoID: 비디오 아이디 
commentID: 댓글 아이디(PK)
comment: 댓글내용
userID: 작성자(user테이블)FK
username

영상 like
likeID
videoID 
userID 
username

재생목록 최초 생성자 - 다같이 공유 / 개인 재생목록 
재생목록 :
listID : PK 재생목록 아이디
userID: 재생목록 생성자
username
videoID 
listName: 재생목록 이름 - 생성자만 입력 가능  
listDesc: 재생목록 설명 - 생성자만 입력 가능 
isPublic :0 1 수정 여부 결정

재생목록 like
로그인한 사용자 이름과 listID를 받아서 이 영상을 기존에 좋아요를 눌렀는지 아닌지 
likeID: 좋아요 아이디(일련번호)
listID - userID 
username

재생목록 신고 기능 hate
hateID
listID - userID 
username

**Comment by hajeong815** [comment]
[DB설계서](https://github.com/Sooktube/Sooktube/wiki/DB%EC%84%A4%EA%B3%84%EC%84%9C)
