### ISSUE TITLE
동영상, 재생목록 자체의 좋아요, 싫어요 API 수정 필요 

### ISSUE THREAD

**Issue by juajang** [Sooktube/Sooktube#6]
### 동영상 자체에 대한 좋아요/싫어요 기능
<좋아요>
``` [POST]/api/like/video/{videoID}/{username} ```
<좋아요 취소>
``` [DELETE]/api/like/video/revert/{videoID}/{username} ```

<싫어요>
``` [POST]/api/dislike/video/{videoID}/{username} ```
<싫어요 취소>
``` [DELETE]/api/dislike/video/revert/{videoID}/{username} ```

### 각 재생목록에 대한 좋아요/싫어요 기능

<좋아요>
``` [POST]/api/video/list/likeList/{listID}/{username} ```
<좋아요 취소>
``` [DELETE]/api/video/list/revert/like/{listID}/{username} ```

<싫어요>
``` [POST]/api/video/list/dislikeList/{listID}/{username} ```
<싫어요 취소>
``` [DELETE]/api/video/list/revert/dislike/{listID}/{username} ```

###  >> response로 좋아요 개수, 싫어요 개수가 오도록 변경 필요함

```json
[
    4,
    -5
]
```

**Comment by hajeong815** [comment]
wiki의 rest api 명세서 확인
