### ISSUE TITLE
좋아요 버튼이 눌린 채로 싫어요 버튼을 눌렀을 때 좋아요 취소가 되지 않음 

### ISSUE THREAD

**Issue by juajang** [Sooktube/Sooktube#7]
#### <추천>
 ` [POST]/api/video/list/like/{listID}/{videoID}/{username}`
#### <비추천>
 `[POST]/api/video/list/dislike/{listID}/{videoID}/{username}`

좋아요 버튼이 눌린 채로 싫어요 버튼을 눌러도 좋아요 값이 그대로 남아 있는 문제가 있습니다 

![image](https://user-images.githubusercontent.com/36043024/90321275-2d2f3600-df83-11ea-8d16-d995266e1520.png)

**Comment by hajeong815** [comment]
wiki의 rest api 명세서 확인
