### ISSUE TITLE
앞으로의 기능 ...

### ISSUE THREAD

**Issue by juajang** [Sooktube/Sooktube#9]
### 새로 추가할 기능
> 대댓글 

> 인피니티 스크롤링: 리스트로 불러오는 모든 api 수정 필요함 

> 동영상 페이지 옆에 동영상 추천 기능 
>> 탭 형식으로 전환 
>> - 이 동영상이 어떤 재생목록에 추가 되어있다면 그 재생목록의 다른 영상들 
>> - 업로더가 올린 다른 영상들

> 재생목록 복사 기능: 기존의 재생목록에서 복사 버튼을 누르면 재생목록 만들기 페이지로 넘어가서 제목과 설명을 다시 설정
>> 복사된 재생목록 페이지에서는 원본 재생목록 페이지가 있음을 알려줌 (링크 걸기) 
>> 복사된 재생목록 페이지에서는 다시 복사는 불가능, 공유도 불가능  

### 개선 사항 
- 비디오 리스트에 좋아요 개수 추가 필요 
- 재생목록 만들때 글자수 제한 필요
- 재생목록에서 public 속성이 아님을 보여주기, public이 아니라면 추천/비추천 버튼도 없음 
- 썸네일 올리는 페이지 개선 필요 (비율 정해진대로만)
- 재생목록 업로더만 영상 삭제 가능한 기능

**Comment by hajeong815** [comment]
@JangJua @grapefruittt 

동영상 페이지 옆에 동영상 추천 기능 중
 > **이 동영상이 어떤 재생목록에 추가되어 있다면 그 재생목록의 다른 영상들**

위의 경우 재생목록에서 실제로 추천+비추천 수가 5 이상인 영상들만(재생목록 주제에 어울린다고 추천을 받은 영상들) 사용자에게 추천해 주어야 함. 

**이 상황에서 발생할 수 있는 경우의 수**

1. 사용자가 현재 시청하고 있는 영상이 해당 재생목록에서 추천+비추천 수가 5 미만이어서 실제 재생목록에 추가되지 않은 영상일 경우
2. 사용자가 현재 시청하고 있는 영상이 해당 재생목록에서 추천+비추천 수가 5 이상이 되어 재생목록에 실제로 추가된 영상일 경우

> 1의 경우, 해당 재생목록 내의 다른 영상(추천+비추천 수가 5 이상인 영상)을 "추천"한다고 해도 사용자가 현재 시청중인 영상과 비슷한 주제가 아닐 가능성이 높음. 

> 따라서 해당 영상이 포함된 재생목록 내 영상을 무조건적으로 추천하기 보다는 사용자에게 지금 시청한 영상이 포함되어 있는 재생목록을 보여주고, 현재 시청 영상을 해당 재생목록에 추천/비추천하는 사용자 시나리오 제시

<예상 UI>
![videorecommendUI](https://user-images.githubusercontent.com/62226517/90839972-c4392b00-e393-11ea-938c-5f716f518e1a.PNG)

**Comment by hajeong815** [comment]
API에서 현재 시청 중인 영상이 재생목록에서 추천+비추천 수 5 이상인 영상에서만 해당 재생목록의 다른 영상 및 listID, listName, listDesc 등 리턴

**Comment by hajeong815** [comment]
* **username별 영상 URL 및 영상 정보 불러오기**

`[GET]/api/video/desc/url/user/{username}`


* **모든 재생목록 표시(_DB에 저장되어 있는 정보[제목, 설명 등]만 표시 및 사용자 좋아요/싫어요 여부 표시_)**

`[GET]/api/video/list/{username}`


* **username별 재생목록 불러오기(해당 사용자가 생성한 재생목록)**

`[GET]/api/video/list/by/username/{username}`



* **각 재생목록에 저장되어 있는 "모든" 동영상 접근 URL 목록 및 영상(이름, 설명, 생성날짜 등)**

`[GET]/api/video/list/desc/URL/{listID}/{username}`

listID는 재생목록 ID -> 각 재생목록에 대한 동영상들의 URL을 List 형태로 한 번에 리턴


* **재생목록 내 동영상 중 좋아요+싫어요 수가 5 "이상"인 동영상 정보 및 URL**

`[GET]/api/video/list/desc/URL/GTEQ/5/{listID}/{username}`


* **videoTitle별 검색(모든 영상의 정보가 있는 VIDEO테이블에서 검색. 재생목록에 추가되어 있지 않은 영상들도 검색 가능)**

`[GET]/api/video/search/title/{videoTitle}/listID/{listID}/user/{username}`


* **재생목록 제목 검색**

`[GET]/api/video/list/search/name/{listName}`


* **재생목록 내 영상에 대한 제목 검색**

`[GET]/api/video/list/listID/{listID}/user/{username}/search/title/{videoTitle}`

**Comment by hajeong815** [comment]
[API 변경사항 확인](https://github.com/Sooktube/Sooktube/wiki/Pagination-&-%EC%B5%9C%EC%8B%A0%EC%88%9C-%EC%B6%94%EC%B2%9C%EC%88%9C-%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EA%B4%80%EB%A0%A8-API-%EB%B3%80%EA%B2%BD%EC%82%AC%ED%95%AD#%EB%B3%80%EA%B2%BD%EC%82%AC%ED%95%AD)
@JangJua @grapefruittt
